HOST = "127.0.0.1"  # Standard loopback interface address (localhost)
PORT = 65432  # Port to listen on
PORT2 = 23456
BUFFER_SIZE = 100000  # Send 4096 bytes each time step
SEPARATOR = "<SEPARATOR>"  # SEPARATOR to separate the data fields
MESSAGE_TAG = "<MSG>"
FILENAME_TAG = "<FILENAME>"
FILE_TAG = "<FILEDATA>"
SIZE_TAG = "<SIZE>"
END_TAG = "<END>"
PUBLIC_KEY = "<PUBLIC_KEY>"
PATH_TO_PRIVATE_KEY = "/keys/private_key/private_key.pem"
PATH_TO_PUBLIC_KEY = "/keys/public_key/public_key.pem"
PARAMETERS_TAG = "<PARAM>"
TAG = 0
DATA = 1
CONTENT = 0
PARAMS = 1
PARAMS2 = 2
TYPE = 1
SIZE = 1
